# Generated by Django 4.0.6 on 2022-08-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='yazar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.blogger'),
        ),
    ]
