# Generated by Django 4.0.6 on 2022-08-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blogger_alter_blog_yazar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='yazar',
            new_name='blogger',
        ),
    ]
