# Generated by Django 4.0.6 on 2022-08-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_blogger_blog_yazar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogger',
            new_name='Bloger',
        ),
    ]
